# Generated by Django 3.0.5 on 2020-04-19 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_Name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cust_Location', models.CharField(max_length=100, null=True)),
                ('checkIn_Time', models.DateTimeField(null=True)),
                ('checkOut_Time', models.DateTimeField(null=True)),
                ('date_Book', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('HotelPolicy', models.TextField(null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Single Room', 'Single Room'), ('Double Sharing', 'Double Sharing'), ('Triple Sharing', 'Triple Sharing'), ('Room for 4', 'Room for 4')], max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amenities', models.CharField(choices=[('AC', 'AC'), ('TV', 'TV'), ('Kitchen', 'Kitchen'), ('Free Wifi', 'Free Wifi'), ('Mini Fridge', 'Mini Fridge'), ('Power Backup', 'Power Backup'), ('Geyser', 'Geyser'), ('Parking Facility', 'Parking Facility'), ('Card Payment', 'Card Payment'), ('CCTV Camera', 'CCTV Camera'), ('Daily Housekeeping', 'Daily Housekeeping'), ('24/7 CheckIn', '24/7 CheckIn'), ('Parking Facility', 'Parking Facility'), ('Coffee/Tea Maker', 'Coffee/Tea Maker'), ('Fan', 'Fan')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('Room Available', 'Room Available'), ('Room Unavailable', 'Room Unavailable')], max_length=100, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_Booking', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Confirm Booking', 'Confirm Booking')], max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb.Customer')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb.Hotel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb.Room')),
            ],
        ),
    ]
