# Generated by Django 3.0.5 on 2020-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0002_auto_20200419_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='thumb1',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb10',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb11',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb2',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb3',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb4',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb5',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb6',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb7',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb8',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumb9',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
