# Generated by Django 3.0.5 on 2020-04-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0003_auto_20200419_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
