# Generated by Django 3.0.5 on 2020-04-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0004_auto_20200420_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(choices=[('AC', 'AC'), ('TV', 'TV'), ('Kitchen', 'Kitchen'), ('Free Wifi', 'Free Wifi'), ('Mini Fridge', 'Mini Fridge'), ('Power Backup', 'Power Backup'), ('Geyser', 'Geyser'), ('Parking Facility', 'Parking Facility'), ('Card Payment', 'Card Payment'), ('CCTV Camera', 'CCTV Camera'), ('Daily Housekeeping', 'Daily Housekeeping'), ('24/7 CheckIn', '24/7 CheckIn'), ('Parking Facility', 'Parking Facility'), ('Coffee/Tea Maker', 'Coffee/Tea Maker'), ('Fan', 'Fan')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Double Sharing', 'Double Sharing'), ('Triple Sharing', 'Triple Sharing'), ('Room for 4', 'Room for 4')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Room Available', 'Room Available'), ('Room Unavailable', 'Room Unavailable')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
