# Generated by Django 3.0.4 on 2020-04-22 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rb', '0005_auto_20200422_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_Location',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkIn_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkOut_Time',
            field=models.TimeField(null=True),
        ),
    ]
