# Generated by Django 3.0.4 on 2020-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0006_auto_20200422_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkIn_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkOut_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cust_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_Book',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
