# Generated by Django 3.0.4 on 2020-04-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0007_auto_20200422_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
