# Generated by Django 3.0.5 on 2020-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0008_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_Book',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkIn_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkOut_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
