# Generated by Django 3.0.5 on 2020-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0009_auto_20200422_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMENITIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(to='rb.AMENITIES'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ManyToManyField(to='rb.CATEGORY'),
        ),
    ]
