# Generated by Django 3.0.5 on 2020-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0010_auto_20200422_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.IntegerField(null=True),
        ),
    ]
