# Generated by Django 3.0.5 on 2020-04-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0011_booking_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
