# Generated by Django 3.0.5 on 2020-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0012_booking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
