# Generated by Django 3.0.5 on 2020-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0013_hotel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
