# Generated by Django 3.0.5 on 2020-04-25 05:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0014_auto_20200424_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'AC'), ('TV', 'TV'), ('Kitchen', 'Kitchen'), ('Free Wifi', 'Free Wifi'), ('Mini Fridge', 'Mini Fridge'), ('Power Backup', 'Power Backup'), ('Geyser', 'Geyser'), ('Parking Facility', 'Parking Facility'), ('Card Payment', 'Card Payment'), ('CCTV Camera', 'CCTV Camera'), ('Daily Housekeeping', 'Daily Housekeeping'), ('24/7 CheckIn', '24/7 CheckIn'), ('Parking Facility', 'Parking Facility'), ('Coffee/Tea Maker', 'Coffee/Tea Maker'), ('Fan', 'Fan')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Single Room', 'Single Room'), ('Double Sharing', 'Double Sharing'), ('Triple Sharing', 'Triple Sharing'), ('Room for 4', 'Room for 4')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AMENITIES',
        ),
        migrations.DeleteModel(
            name='CATEGORY',
        ),
    ]
