# Generated by Django 3.0.5 on 2020-04-25 05:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0015_auto_20200425_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'AC'), ('TV', 'TV'), ('Kitchen', 'Kitchen'), ('Free Wifi', 'Free Wifi'), ('Mini Fridge', 'Mini Fridge'), ('Power Backup', 'Power Backup'), ('Geyser', 'Geyser'), ('Parking Facility', 'Parking Facility'), ('Card Payment', 'Card Payment'), ('CCTV Camera', 'CCTV Camera'), ('Daily Housekeeping', 'Daily Housekeeping'), ('24/7 CheckIn', '24/7 CheckIn'), ('Coffee/Tea Maker', 'Coffee/Tea Maker'), ('Fan', 'Fan')], max_length=300, null=True),
        ),
    ]
