# Generated by Django 3.0.4 on 2020-04-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0016_auto_20200425_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkIn_Time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkOut_Time',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkIn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkOut',
            field=models.DateField(null=True),
        ),
    ]
