# Generated by Django 3.0.5 on 2020-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0018_hotel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkIn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkOut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='mobile',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
